### ISSUE TITLE
index.html isn't being excluded

### ISSUE THREAD

**Issue by antaenc** [qoomon/aws-s3-bucket-browser#46]
Using the current index.html, the keyExcludePatterns: [/^index\.html$/] doesn't appear to be working. I'm getting the index.html in the listing of objects.

**Comment by qoomon** [comment]
Ah I see. In your case you need to set `keyExcludePatterns: [/^x86_64/index\.html$/]`

**Comment by qoomon** [comment]
> Many thanks, I had to modify it to /^x86_64\/index\.html$/ to escape the slash.

Sure my bad.

> I can't seem to work out how to exclude the repodata/ folder that is also there, I've tried a few combinations but no joy. 

Unfortunately this is not possible at the moment  because a folder is just a common prefix and is not filtered by `keyExcludePatterns`these are only filters for fully qualified keys e.g. `repodata/assets/foo.zip´

However I'll try to make it work also e.g. `keyExcludePatterns: [/^repodata\//]`

**Comment by qoomon** [comment]
I was wrong it is working already you just need to find the right key prefix. your excludes should look like these `keyExcludePatterns: [/^x86_64\/index\.html$/, /^x86_64\/repodata\// ]`

**Comment by qoomon** [comment]
done. feel free to try version `2.0.0`
